WebTimeSheetManagement/Controllers/AllRolesController.cs
using EventApplicationCore.Library;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebTimeSheetManagement.Concrete;
using WebTimeSheetManagement.Filters;
using WebTimeSheetManagement.Interface;
using WebTimeSheetManagement.Models;
using WebTimeSheetManagement.Service;

namespace WebTimeSheetManagement.Controllers
{
    [ValidateSuperAdminSession]
    public class AllRolesController : Controller
    {
        IAssignRoles _IAssignRoles;
        IUsers _IUsersConcrete;
        public AllRolesController()
        {
            _IAssignRoles = new AssignRolesConcrete();
            _IUsersConcrete = new UsersConcrete();
        }

        // GET: AllRoles
        public ActionResult Roles()
        {
            return View();
        }

        public ActionResult LoadRolesData()
        {
            try
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                int recordsTotal = 0;

                var rolesData = _IAssignRoles.ShowallRoles(sortColumn, sortColumnDir, searchValue);
                recordsTotal = rolesData.Count();
                var data = rolesData.Skip(skip).Take(pageSize).ToList();

                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult RemovefromRole(string RegistrationID)
        {
            try
            {
                if (string.IsNullOrEmpty(RegistrationID))
                {
                    return RedirectToAction("Roles");
                }

                var role = _IAssignRoles.RemovefromUserRole(RegistrationID);
                RegistrationViewDetailsModel user = _IUsersConcrete.GetUserDetailsByRegistrationID(Convert.ToInt32(RegistrationID));
                RegistrationViewDetailsModel userSuperAdmin = _IUsersConcrete.GetAdminDetailsByRegistrationID(Convert.ToInt32(Session["SuperAdmin"]));
                EmailUtility.SendMailAsync(EmailConstants.RemoveRole, GetEmailTemplate(RegistrationID, user), new List<string>() { user.EmailID }, new List<string>() { userSuperAdmin.EmailID }, EmailUtility.EnumEmailSentType.Login);
                return Json(role);
            }
            catch (Exception)
            {
                return Json(false);
            }
        }

        private string GetEmailTemplate(string RegistrationID, RegistrationViewDetailsModel user)
        {
            return $"Hi {user.Name},<br/><br/><br>The admin {Session["Username"]} has revovked your Timesheet Access.";
        }


    }
}

WebTimeSheetManagement/Views/AllRoles/Roles.cshtml
@{
    ViewBag.Title = "Roles";
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}



<link href="~/Scripts/dataTablesScripts/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/Scripts/dataTablesScripts/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/dataTablesScripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTablesScripts/dataTables.bootstrap4.min.js"></script>
<style type="text/css">
    #scrolly {
        width: 1000px;
        height: 450px;
        overflow: auto;
        overflow-y: hidden;
        margin: 0 auto;
        white-space: nowrap;
    }
</style>



<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Roles</div>
            <div class="panel-body">

                <table id="myTable" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>RegistrationID</th>
                            <th>Name</th>
                            <th>AssignToAdmin</th>
                            <th>RemoveRole</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#myTable").DataTable({
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "ajax": {
                "url": "@Url.Action("LoadRolesData", "AllRoles")",
                "type": "POST",
                "datatype": "json"
            },
            "columnDefs":
            [{
                "targets": [0],
                "visible": false,
                "orderable": true,
                "searchable": false
                },
                    {
                        "targets": [2],
                        "visible": true,
                        "orderable": false,
                        "searchable": false
                    },
            {
                "targets": [3],
                "visible": true,
                "searchable": false,
                "orderable": false
                    }],
            order: [[1, 'asc']],
            "columns": [
                { "data": "RegistrationID", "name": "RegistrationID", "autoWidth": true },
                { "data": "Name", "name": "Name", "autoWidth": true },

                                    {
                                        "render": function (data, type, full, meta) {
                                            if (full.AssignToAdmin == "*Not Assigned*") {
                                                return "<lable class='alert-danger'>*Not Assigned*</lable>";
                                            }
                                            else {

                                                return "<lable class='alert-success'>" + full.AssignToAdmin + "</lable>";
                                            }
                                        }
                                    },


                {
                    "render": function (data, type, full, meta) {
                        if (full.AssignToAdmin == "*Not Assigned*") {
                            return "*Not Assigned*";
                        }
                        else {
                            return "<a href='#' class='btn btn-danger' onclick=Removefromrole('" + full.RegistrationID + "'); >Remove Role</a>";
                        }
                    }
                },
            ]

        });
    });
</script>

            <script type="text/javascript">

    function Removefromrole(ID) {
        if (confirm("Are you sure you want to Remove Role ...?")) {
            Removerole(ID);
        }
        else {
            return false;
        }
    }
    function Removerole(ID) {
        var url = '@Url.Action("RemovefromRole", "AllRoles")';
        $.post(url, { RegistrationID: ID }, function (data) {
            if (data) {
                oTable = $('#myTable').DataTable();
                oTable.draw();
            }
            else {
                alert("Something Went Wrong!");
            }
        });
    }
            </script>