WebTimeSheetManagement/Controllers/AllUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebTimeSheetManagement.Concrete;
using WebTimeSheetManagement.Filters;
using WebTimeSheetManagement.Interface;

namespace WebTimeSheetManagement.Controllers
{
    [ValidateSuperAdminSession]

    public class AllUsersController : Controller
    {
        private IUsers _IUsers;
        public AllUsersController()
        {
            _IUsers = new UsersConcrete();
        }

        // GET: AllUsers
        public ActionResult Users()
        {
            return View();
        }

        public ActionResult LoadUsersData()
        {
            try
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                int recordsTotal = 0;

                var rolesData = _IUsers.ShowallUsers(sortColumn, sortColumnDir, searchValue);
                recordsTotal = rolesData.Count();
                var data = rolesData.Skip(skip).Take(pageSize).ToList();

                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult UserDetails(int? RegistrationID)
        {
            try
            {
                if (RegistrationID == null)
                {

                }
                var userDetailsResponse = _IUsers.GetUserDetailsByRegistrationID(RegistrationID);
                return PartialView("_UserDetails", userDetailsResponse);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult Admin()
        {
            return View();
        }

        public ActionResult LoadAdminsData()
        {
            try
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                int recordsTotal = 0;

                var rolesData = _IUsers.ShowallAdmin(sortColumn, sortColumnDir, searchValue);
                recordsTotal = rolesData.Count();
                var data = rolesData.Skip(skip).Take(pageSize).ToList();

                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult AdminDetails(int? RegistrationID)
        {
            try
            {
                if (RegistrationID == null)
                {

                }
                var userDetailsResponse = _IUsers.GetAdminDetailsByRegistrationID(RegistrationID);
                return PartialView("_UserDetails", userDetailsResponse);
            }
            catch (Exception)
            {
                throw;
            }
        }

    }
}

WebTimeSheetManagement/Controllers/SuperAdminController.cs
using Dapper;
using EventApplicationCore.Library;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using WebTimeSheetManagement.Concrete;
using WebTimeSheetManagement.Filters;
using WebTimeSheetManagement.Helpers;
using WebTimeSheetManagement.Interface;
using WebTimeSheetManagement.Models;

namespace WebTimeSheetManagement.Controllers
{
    [ValidateCommonAdminSession]
    public class SuperAdminController : Controller
    {
        private IRegistration _IRegistration;
        private IRoles _IRoles;
        private IAssignRoles _IAssignRoles;
        private ICacheManager _ICacheManager;
        private IUsers _IUsers;
        private IProject _IProject;
        private ITimeSheet _ITimeSheet;
        

        public SuperAdminController()
        {
            _IRegistration = new RegistrationConcrete();
            _IRoles = new RolesConcrete();
            _IAssignRoles = new AssignRolesConcrete();
            _ICacheManager = new CacheManager();
            _IUsers = new UsersConcrete();
            _IProject = new ProjectConcrete();
            _ITimeSheet = new TimeSheetConcrete();
        }

        // GET: SuperAdmin
        public ActionResult Dashboard()
        {
            try
            {
                var datadashboard = _ITimeSheet.GetDashboardDataByID(Convert.ToString(Session["SuperAdmin"]), "SuperAdminUser");
                ViewBag.DashboardData = datadashboard;
                var adminCount = _ICacheManager.Get<object>("AdminCount");
                var statusCountdashboard = _ITimeSheet.GetDashboardStatusDataByID(Convert.ToString(Session["SuperAdmin"]), "SuperAdminUser");
                var LegalStatusCountdashboardData = _ITimeSheet.GetDashboardLegalStatusDataByAdminID(Convert.ToString(Session["SuperAdmin"]), "SuperAdminUser");

                ViewBag.StatusCountdashboard = statusCountdashboard;
                ViewBag.LegalStatusCountdashboardData = LegalStatusCountdashboardData;
                if (adminCount == null)
                {
                    var admincount = _IUsers.GetTotalAdminsCount();
                    _ICacheManager.Add("AdminCount", admincount);
                    ViewBag.AdminCount = admincount;
                }
                else
                {
                    ViewBag.AdminCount = adminCount;
                }

                var usersCount = _ICacheManager.Get<object>("UsersCount");

                if (usersCount == null)
                {
                    var userscount = _IUsers.GetTotalUsersCount();
                    _ICacheManager.Add("UsersCount", userscount);
                    ViewBag.UsersCount = userscount;
                }
                else
                {
                    ViewBag.UsersCount = usersCount;
                }

                var projectCount = _ICacheManager.Get<object>("ProjectCount");

                if (projectCount == null)
                {
                    var projectcount = _IProject.GetTotalProjectsCounts();
                    _ICacheManager.Add("ProjectCount", projectcount);
                    ViewBag.ProjectCount = projectcount;
                }
                else
                {
                    ViewBag.ProjectCount = projectCount;
                }

                return View();
            }
            catch (Exception)
            {

                throw;
            }
        }
        public ActionResult TSCountData()
        {
            var datadashboard = _ITimeSheet.GetDashboardDataByID(Convert.ToString(Session["SuperAdmin"]), "SuperAdminUser");
            ViewBag.DashboardData = datadashboard;
            return View();
        }
        public ActionResult StatusData()
        {
            var statusCountdashboard = _ITimeSheet.GetDashboardStatusDataByID(Convert.ToString(Session["SuperAdmin"]), "SuperAdminUser");
            ViewBag.statusCountdashboard = statusCountdashboard;
            return View();
        }

        public ActionResult LegalStatusData()
        {
            var LegalStatusCountdashboardData = _ITimeSheet.GetDashboardLegalStatusDataByAdminID(Convert.ToString(Session["SuperAdmin"]), "SuperAdminUser");
            ViewBag.LegalStatusCountdashboardData = LegalStatusCountdashboardData;
            return View();
        }


        [HttpGet]
        public ActionResult CreateAdmin()
        {
            Registration reg = new Registration();
            reg.LegalStatusList = _IRegistration.GetAllLegalStatusList();
            return View(reg);
        }

        [HttpPost]
        public ActionResult CreateAdmin(Registration registration)
        {

            try
            {
                var isUsernameExists = _IRegistration.CheckUserNameExists(registration.Username);

                if (isUsernameExists)
                {
                    ModelState.AddModelError("", errorMessage: "Username Already Used try unique one!");
                }
                else
                {
                    registration.CreatedOn = DateTime.Now;
                    registration.RoleID = _IRoles.getRolesofUserbyRolename("Admin");
                    registration.Password = EncryptionLibrary.EncryptText(registration.Password);
                    registration.ConfirmPassword = EncryptionLibrary.EncryptText(registration.ConfirmPassword);
                    if (_IRegistration.AddUser(registration) > 0)
                    {
                        TempData["MessageRegistration"] = "Data Saved Successfully!";
                        return RedirectToAction("CreateAdmin");
                    }
                    else
                    {
                        return View("CreateAdmin", registration);
                    }
                }

                return RedirectToAction("Dashboard");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult AssignRoles()
        {
            try
            {
                AssignRolesModel assignRolesModel = new AssignRolesModel();
                assignRolesModel.ListofAdmins = _IAssignRoles.ListofAdmins();
                assignRolesModel.ListofUser = _IAssignRoles.GetListofUnAssignedUsers(Convert.ToString(Session["OrganizationId"]));
                return View(assignRolesModel);
            }
            catch (Exception)
            {

                throw;
            }
        }
        public ActionResult LoadUsersData()
        {
            try
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                int recordsTotal = 0;
                
                var rolesData = _IAssignRoles.GetListofUnAssignedUsers(Convert.ToString(Session["OrganizationId"]),sortColumn, sortColumnDir, searchValue);
                recordsTotal = rolesData.Count();
                var data = rolesData.Skip(skip).Take(pageSize).ToList();

                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public ActionResult AssignRoles(List<UserModel> SelectedUsers,string assignToAdmin)
        {
            try
            {
                AssignRolesModel objassign = new AssignRolesModel();
                objassign.ListofUser = SelectedUsers;
                if (objassign.ListofUser == null || string.IsNullOrEmpty(assignToAdmin))
                {
                    TempData["MessageErrorRoles"] = string.IsNullOrEmpty(assignToAdmin)?"Please select the admin to assign" : "There are no Users to Assign Roles";
                    objassign.ListofAdmins = _IAssignRoles.ListofAdmins();
                    objassign.ListofUser = _IAssignRoles.GetListofUnAssignedUsers(Convert.ToString(Session["OrganizationId"]));
                    return View(objassign);
                }

                objassign.AssignToAdmin = Convert.ToInt32(assignToAdmin);

                var SelectedCount = (from User in objassign.ListofUser
                                     where User.selectedUsers == true
                                     select User).Count();

                if (SelectedCount == 0)
                {
                    TempData["MessageErrorRoles"] = "You have not Selected any User to Assign Roles";
                    objassign.ListofAdmins = _IAssignRoles.ListofAdmins();
                    objassign.ListofUser = _IAssignRoles.GetListofUnAssignedUsers(Convert.ToString(Session["OrganizationId"]));
                    return View(objassign);
                }

                if (ModelState.IsValid)
                {
                    objassign.CreatedBy = Convert.ToInt32(Session["SuperAdmin"]);

                    _IAssignRoles.SaveAssignedRoles(objassign);
                    TempData["MessageRoles"] = "Roles Assigned Successfully!";
                }

                objassign = new AssignRolesModel();
                objassign.ListofAdmins = _IAssignRoles.ListofAdmins();
                objassign.ListofUser = _IAssignRoles.GetListofUnAssignedUsers(Convert.ToString(Session["OrganizationId"]));

WebTimeSheetManagement/Views/SuperAdmin/AssignRoles.cshtml
@model WebTimeSheetManagement.Models.AssignRolesModel
@{
    ViewBag.Title = "AssignRoles";
    string CurrentName = Convert.ToString(Session["SuperAdmin"]);
    if (!string.IsNullOrEmpty(CurrentName))
    {
        Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
}



<link href="~/Scripts/dataTablesScripts/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/Scripts/dataTablesScripts/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/dataTablesScripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTablesScripts/dataTables.bootstrap4.min.js"></script>
<style type="text/css">
    #scrolly {
        width: 1000px;
        height: 450px;
        overflow: auto;
        overflow-y: hidden;
        margin: 0 auto;
        white-space: nowrap;
    }
</style>
    <div class="panel panel-default">
        <div class="panel-heading">Choose Admin</div>
        <div class="panel-body">

            @if (TempData["MessageRoles"] != null)
            {
                <p class="alert alert-success" id="successMessage">@TempData["MessageRoles"] </p>
            }

            @if (TempData["MessageErrorRoles"] != null)
            {
                <p class="alert alert-danger" id="successMessage">@TempData["MessageErrorRoles"] </p>
            }

            @Html.AntiForgeryToken()

            <div class="row">
                <div class="col-md-4">
                    @Html.DropDownListFor(a => a.RegistrationID, new SelectList(Model.ListofAdmins, "RegistrationID", "Name"), new { @id="adminAssigned", @class = "form-control" })
                    @Html.ValidationMessageFor(a => a.RegistrationID)
                </div>
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                </div>
            </div>


        </div>
    </div>
    @*<div class="panel panel-default">
            <div class="panel-heading">Choose Users To Assign to Admin</div>
            <div class="panel-body">
                <div class="clearfix"></div>
                <div class="row">


                    @for (var i = 0; i < Model.ListofUser.Count(); i++)
                    {
                        <div class="col-md-4">
                            <div>
                                @Html.CheckBoxFor(it => Model.ListofUser[i].selectedUsers)
                                <label>
                                    @Html.DisplayFor(it => Model.ListofUser[i].Name)
                                    @Html.HiddenFor(it => Model.ListofUser[i].RegistrationID)
                                    @Html.HiddenFor(it => Model.ListofUser[i].Name)
                                </label>
                            </div>
                        </div>


                    }


                </div>
                <br />
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-offset-0 col-md-12">
                            <input type="submit" value="Assign Role" class="btn btn-success" />

                            @Html.ActionLink("Cancel", "Dashboard", "SuperAdmin", null, new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>*@

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">Roles</div>
                <div class="panel-body">

                    <table id="myTable" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>RegistrationID</th>
                                <th>Name</th>
                            </tr>
                        </thead>
                    </table>
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-offset-0 col-md-12">
                                <input type="submit" value="Assign Role" class="btn btn-success" onclick="submit1('asd')" />
                                @Html.ActionLink("Cancel", "Dashboard", "SuperAdmin", null, new { @class = "btn btn-danger" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <link href="https://cdn.datatables.net/s/dt/dt-1.10.10,se-1.1.0/datatables.min.css" rel="stylesheet" />
    <link href="https://gyrocode.github.io/jquery-datatables-checkboxes/1.2.6/css/dataTables.checkboxes.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="https://cdn.datatables.net/s/dt/dt-1.10.10,se-1.1.0/datatables.min.js"></script>
    <script src="https://gyrocode.github.io/jquery-datatables-checkboxes/1.2.6/js/dataTables.checkboxes.min.js"></script>
    <script>
        var selectedUsers = new Array();
        var adminAssigned="";
        $(document).ready(function () {
            $('#adminAssigned').on('change', function () {
                adminAssigned = $(this).val();
                console.log(adminAssigned);
                for (var ind in selectedUsers) {
                    ind.AssignToAdmin = adminAssigned;
                    console.log(selectedUsers);

                }
            });


        var table=$("#myTable").DataTable({
                "processing": true, // for show progress bar
                "serverSide": true, // for process server side
                "filter": true, // this is for disable filter (search box)
                "orderMulti": false, // for disable multiple column at once
                "ajax": {
                    "url": "@Url.Action("LoadUsersData", "SuperAdmin")",
                    "type": "POST",
                    "datatype": "json"
            },
            "drawCallback": function (settings) {
                // Here the response
                var response = settings.json;
                console.log(settings);
                console.log(response);
            },
                "columnDefs":
                    [{
                        "targets": 0,
                        "visible": true,
                        'checkboxes': {
                            'selectRow': true
                        },
                    },
                        {
                            "targets": [1],
                            "visible": true,
                            "searchable": true
                        },
                    ],

                "columns": [
                    { "data": "Name", "name": "Name", "autoWidth": true },
                    { "data": "Name", "name": "Name", "autoWidth": true }
            ],
            'select': {
                'style': 'multi'
            },

        });

            table.on('deselect', function (e, dt, type, indexes) {
                //get the row information for the row deselected.
                for (var ind of indexes) {
                    console.log(ind);
                    console.log(dt.row(ind).data())
                    var filtered = selectedUsers.filter((item) => item.RegistrationID !== dt.row(ind).data().RegistrationID);
                    selectedUsers = filtered;
                }
                //    for (var i = 0; i < selectedUsers.length; i++){
                //        var regId = dt.row(ind).data().RegistrationID;
                //        if (selectedUsers[i].RegistrationID == regId)
                //            selectedUsers[i].SelectedUsers = false;
                //    }
                //}
            });
            table.on('select', function (e, dt, type, indexes) {
                //get the row information for the row selected.
                console.log(indexes);
                for (var ind of indexes) {
                    var find = false;
                    for (var selected of selectedUsers) {
                        if (selected.RegistrationID == dt.row(ind).data().RegistrationID) {
                            find = true;
                            break;
                        }
                    }
                    if (!find) {
                        selectedUsers.push(dt.row(ind).data())
                    }
                }
                for (var sel of selectedUsers) {
                    sel.selectedUsers = true;
                }
            });
        });

    var ss = [];
    function Assignrole(id) {
        if ($('#' + id).is(":checked")) {
            ss.push(id);
        }
        else {
            const index = ss.indexOf(id)
            ss.splice(index, 1);
        }
        }

        function submit1(asd) {
            console.log($("#adminAssigned option:selected").val());
            var url ="@Url.Action("AssignRoles", "SuperAdmin")";
            $.post(url, { SelectedUsers: selectedUsers, assignToAdmin: adminAssigned }, function (data) {
                if (data) {
                    oTable = $('#myTable').DataTable();
                    oTable.draw();
                }
                else {
                    alert("Something Went Wrong!");
                }
            });
            console.log(ss);
            console.log('@Model.AssignToAdmin');
            console.log("BALAJI")
            selectedUsers = new Array();
        }



    </script>

WebTimeSheetManagement/Views/SuperAdmin/CreateAdmin.cshtml
@model WebTimeSheetManagement.Models.Registration
@using CaptchaMvc.HtmlHelpers
@{
    ViewBag.Title = "CreateAdmin";
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}

<h4 class="page-header">Create Admin User</h4>
 
<div class="panel panel-default">
    <div class="panel-heading">Create Admin User</div>
    <div class="panel-body">

        @if (TempData["MessageRegistration"] != null)
        {
            <p class="alert alert-success" id="successMessage">@TempData["MessageRegistration"]</p>
        }

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @using (Html.BeginForm("CreateAdmin", "SuperAdmin"))
        {
            @Html.AntiForgeryToken()

            <div class="row">
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @maxlength = 40, @onkeypress = "return onlyspecchar(event);" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.Mobileno, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.TextBoxFor(model => model.Mobileno, new { @class = "form-control", @maxlength = 10, @onkeydown = "return OnlyNumeric(this);" })
                    @Html.ValidationMessageFor(model => model.Mobileno, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.EmailID, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.TextBoxFor(model => model.EmailID, new { @class = "form-control", @maxlength = 50 })
                    @Html.ValidationMessageFor(model => model.EmailID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4" style="margin-top:20px;">
                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.RadioButtonFor(model => model.Gender, "M") @Html.Label("", "Male")
                    @Html.RadioButtonFor(model => model.Gender, "F") @Html.Label("", "Female")
                    <br />
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.Birthdate, new { @class = "form-control", @onkeypress = "alert('Choose Birthdate');" })
                    @Html.ValidationMessageFor(model => model.Birthdate, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-4">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.TextBoxFor(model => model.Username, new { @class = "form-control", @maxlength = 20, @onkeypress = "return onlyspecchar(event);", @onblur = "CheckUsernameExists();" })
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control", @maxlength = 30, })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-lg-4" style="margin-top:20px;">
                    @Html.LabelFor(model => model.LegalStatus, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.DropDownListFor(a => a.LegalStatus, new SelectList(Model.LegalStatusList, "LegalStatus", "LegalStatus"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LegalStatus, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-4" style="margin-top:20px;">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label manadatory" })
                    <br/>
                    @Html.RadioButtonFor(model => model.Status, "Active") @Html.Label("", "Active")
                    @Html.RadioButtonFor(model => model.Status, "Inactive") @Html.Label("", "Inactive")
                    @Html.RadioButtonFor(model => model.Status, "Exit") @Html.Label("", "Exit")
                </div>
            </div>
        <br />
        <div class="row">
            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Create Admin" class="btn btn-success" />
                    @Html.ActionLink("Clear", "CreateAdmin", "SuperAdmin", null, new { @class = "btn btn-danger" })

                    @Html.ActionLink("All Admin", "admin", "AllUsers", null, new { @class = "btn btn-info" })

                </div>
            </div>
        </div>
    }

    </div>
    </div>



<script type="text/javascript">

    $(document).ready(function () {
        $("#Birthdate").datepicker
            ({
                dateFormat: "yy-mm-dd",
                changeMonth: true,
                changeYear: true,
                yearRange: "-100:+100",
                onSelect: function (date) {
                    var dob = new Date(date);
                    var today = new Date();

                    if (dob.getFullYear() + 18 < today.getFullYear()) {

                    }
                    else {
                        $("#Birthdate").val('');
                        alert("You are not eligible for Registration");
                    }
                }
            });
    });

    function OnlyNumeric(evt) {
        var charCode = (evt.which) ? evt.which : evt.keyCode
        if ((charCode < 48 || charCode > 57)) {
            if (charCode == 8 || charCode == 46 || charCode == 0) {
                return true;
            }
            else {
                return false;
            }
        }
    }

    function CheckUsernameExists() {
        var url = "@Url.Action("CheckUserNameExists", "Registration")";
        var source = "#Username";
        $.post(url, { Username: $(source).val() }, function (data) {
            if (data) {
                $(source).val('');
                alert("Username Already Used try unique one!");
            }
            else {

            }
        });
    }

    function onlyspecchar(evt) {
        var charCode = (evt.which) ? evt.which : evt.keyCode
        var txt = String.fromCharCode(charCode)
        if ((txt.match(/^[a-zA-Z\b. ]+$/)) || (txt.match(/^[0-9]+$/)) || (charCode == 64) || (charCode == 45) || (charCode == 46) || (charCode == 95) || (charCode == 41)) {
            return true;
        }
        return false;
    }
</script>